trigger:
  branches:
    include:
      - main
  tags:
    include:
      - v*

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macos-latest"
    windows:
      imageName: "windows-latest"

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      const { execSync } = require('child_process');

      if (process.platform === 'linux') {
        execSync('/usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &');
        console.log('>>> Started xvfb');
      }

      console.log('>>> Compile vscode-test');
      execSync('npm install && npm run compile');

      execSync('cd sample && npm install && npm run compile && npm run test');
    displayName: Run Tests
    env:
      DISPLAY: ":99.0"
