trigger:
  branches:
    include:
      - main
  tags:
    include:
      - v*

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macos-latest"
    windows:
      imageName: "windows-latest"

pool:
  vmImage: $(imageName)

steps:
  - task: UseNode@1
    inputs:
      versionSpec: "10.x"
      addToPath: true
    displayName: "Install Node.js"

  - script: |
      echo ">>> Compile vscode-test"
      npm install
      npm run compile
      echo ">>> Compiled vscode-test"
      cd sample
      echo ">>> Run sample integration test"
      npm install
      npm run compile
      npm test
    displayName: Run Tests
    env:
      DISPLAY: ":99.0"
      npm_config_loglevel: "verbose"
      CI: true
