trigger:
  - "*"
pr:
  - "*"

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macos-latest"
    windows:
      imageName: "windows-latest"

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSource: "spec"
      versionSpec: "10.x"
      checkLatest: true
    displayName: "Install Node.js"

  - script: |
      npm install -g webpack webpack-cli --save-dev
      npm install -g typescript
      npm install
      npx webpack --config webpack.config.js
    displayName: "npm install, run webpack"
    env:
      DISPLAY: ":99.0"
      npm_config_loglevel: "verbose"
